project_id = "ugtaodrvbpfeyhdgmisn"

[functions.test-data-fetch]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-fcm-direct]
verify_jwt = false

[functions.process-push-jobs]
verify_jwt = false

[functions.fetch-historical-data]
verify_jwt = false

[functions.run-backtests]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.track-referral]
verify_jwt = false

[functions.aggregate-4h-candles]
verify_jwt = false