project_id = "ugtaodrvbpfeyhdgmisn"

[functions.send-push-notification]
verify_jwt = false

[functions.send-fcm-direct]
verify_jwt = false

[functions.process-push-jobs]
verify_jwt = false

[functions.fetch-historical-data]
verify_jwt = false

[functions.run-backtests]
verify_jwt = false

# Allow public tracking from landing pages and unauthenticated clients
[functions.track-referral]
verify_jwt = false