
import React from 'react';
import { TrendingUp, Zap, Shield, BarChart3 } from 'lucide-react';

const LandingPage = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-800">
      {/* Navigation */}
      <nav className="flex items-center justify-between p-6 bg-black/20 backdrop-blur-sm">
        <div className="flex items-center space-x-2">
          <TrendingUp className="h-8 w-8 text-emerald-400" />
          <span className="text-2xl font-bold text-white">ForexSignal Pro</span>
        </div>
        <div className="space-x-4">
          <button
            onClick={() => onNavigate('login')}
            className="px-6 py-2 text-white hover:text-emerald-400 transition-colors"
          >
            Login
          </button>
          <button
            onClick={() => onNavigate('signup')}
            className="px-6 py-2 bg-emerald-500 text-white rounded-lg hover:bg-emerald-600 transition-colors"
          >
            Get Started
          </button>
        </div>
      </nav>

      {/* Hero Section */}
      <div className="container mx-auto px-6 py-20">
        <div className="text-center mb-16">
          <h1 className="text-5xl md:text-7xl font-bold text-white mb-6">
            AI-Powered
            <span className="bg-gradient-to-r from-emerald-400 to-blue-400 bg-clip-text text-transparent">
              {" "}Forex Signals
            </span>
          </h1>
          <p className="text-xl text-gray-300 mb-8 max-w-3xl mx-auto">
            Follow high-confidence forex trading signals generated by advanced AI analysis. 
            Maximize your trading potential with automated copy trading and real-time market insights.
          </p>
          <button
            onClick={() => onNavigate('signup')}
            className="px-8 py-4 bg-gradient-to-r from-emerald-500 to-blue-500 text-white text-lg font-semibold rounded-lg hover:shadow-lg hover:shadow-emerald-500/25 transition-all transform hover:scale-105"
          >
            Start Trading Now
          </button>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-3 gap-8 mb-20">
          <div className="bg-white/5 backdrop-blur-sm rounded-xl p-8 border border-white/10 hover:border-emerald-500/50 transition-all">
            <div className="bg-emerald-500/20 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
              <Zap className="h-6 w-6 text-emerald-400" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-3">AI-Powered Signals</h3>
            <p className="text-gray-300">
              Advanced AI analyzes market data to generate high-confidence trading signals with 80%+ accuracy.
            </p>
          </div>

          <div className="bg-white/5 backdrop-blur-sm rounded-xl p-8 border border-white/10 hover:border-emerald-500/50 transition-all">
            <div className="bg-blue-500/20 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
              <Shield className="h-6 w-6 text-blue-400" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-3">Copy Trading</h3>
            <p className="text-gray-300">
              Automatically execute trades based on AI signals with customizable risk management parameters.
            </p>
          </div>

          <div className="bg-white/5 backdrop-blur-sm rounded-xl p-8 border border-white/10 hover:border-emerald-500/50 transition-all">
            <div className="bg-purple-500/20 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
              <BarChart3 className="h-6 w-6 text-purple-400" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-3">Real-time Analytics</h3>
            <p className="text-gray-300">
              Monitor performance with detailed analytics, win rates, and profit/loss tracking in real-time.
            </p>
          </div>
        </div>

        {/* Stats Section */}
        <div className="grid md:grid-cols-4 gap-8 text-center">
          <div className="bg-gradient-to-br from-emerald-500/20 to-emerald-600/20 rounded-xl p-6 border border-emerald-500/30">
            <div className="text-3xl font-bold text-emerald-400 mb-2">85%</div>
            <div className="text-gray-300">Signal Accuracy</div>
          </div>
          <div className="bg-gradient-to-br from-blue-500/20 to-blue-600/20 rounded-xl p-6 border border-blue-500/30">
            <div className="text-3xl font-bold text-blue-400 mb-2">50+</div>
            <div className="text-gray-300">Currency Pairs</div>
          </div>
          <div className="bg-gradient-to-br from-purple-500/20 to-purple-600/20 rounded-xl p-6 border border-purple-500/30">
            <div className="text-3xl font-bold text-purple-400 mb-2">24/7</div>
            <div className="text-gray-300">Market Monitoring</div>
          </div>
          <div className="bg-gradient-to-br from-orange-500/20 to-orange-600/20 rounded-xl p-6 border border-orange-500/30">
            <div className="text-3xl font-bold text-orange-400 mb-2">10k+</div>
            <div className="text-gray-300">Active Traders</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LandingPage;
